CREATE TRIGGER `MESSAGE_BLOC_MONTANT` AFTER INSERT ON `solde_bloquer`
 FOR EACH ROW BEGIN
	DECLARE MSG VARCHAR(500);
	DECLARE DESTINATAIRE VARCHAR(100);

	SET @DESTINATAIRE := (SELECT Mail FROM CLIENT WHERE NUM_CPT=NEW.NUM_CPT) ;

	IF @DESTINATAIRE IS NOT NULL THEN

		SET @MSG := CONCAT('VOUS AVEZ UN MONTANT DE : ',NEW.MT_BLOC,' BLOQUER DANS VOTRE COMPTE TRESORE N°: ',NEW.NUM_CPT) ;
		INSERT INTO MESSAGE (DESTINATAIRE,MSG)
		VALUE
				(@DESTINATAIRE,@MSG);
	END IF ;
END