CREATE TRIGGER `MESSAGE_DEBIT_CREDIT` AFTER UPDATE ON `client`
 FOR EACH ROW BEGIN
	DECLARE MSG VARCHAR(500);
	DECLARE DESTINATAIRE VARCHAR(100);

	SET @DESTINATAIRE := (SELECT Mail FROM CLIENT WHERE NUM_CPT=NEW.NUM_CPT) ;

	IF @DESTINATAIRE IS NOT NULL THEN
		IF NEW.SOLDE_ACTUEL < OLD.SOLDE_ACTUEL  THEN
			SET @MSG := CONCAT('VOTRE COMPTE TRESORE N°: ',NEW.NUM_CPT,' A ETE DEBITER, VOTRE SOLDE ACTUEL EST : ',NEW.SOLDE_ACTUEL) ;
			INSERT INTO MESSAGE (DESTINATAIRE,MSG)
			VALUE
				(@DESTINATAIRE,@MSG);
		ELSE IF NEW.SOLDE_ACTUEL > OLD.SOLDE_ACTUEL THEN
			SET @MSG := CONCAT('VOTRE COMPTE TRESORE N°: ',NEW.NUM_CPT,' A ETE CREDITER, VOTRE SOLDE ACTUEL EST : ',NEW.SOLDE_ACTUEL) ;
			INSERT INTO MESSAGE (DESTINATAIRE,MSG)
			VALUE
				(@DESTINATAIRE,@MSG);
			END IF;
		END IF;
	END IF;

END