CREATE TRIGGER `MESSAGE_DEBIT_CREDIT` AFTER UPDATE ON `client`
 FOR EACH ROW BEGIN
	DECLARE MSG VARCHAR(500);
	DECLARE DESTINATAIRE VARCHAR(100);

	SET @DESTINATAIRE := (SELECT Mail FROM CLIENT WHERE NUM_CPT=NEW.NUM_CPT) ;

	IF @DESTINATAIRE IS NOT NULL THEN
		IF OLD.SOLDE_ACTUEL > NEW.SOLDE_ACTUEL  THEN
			SET @MSG := CONCAT('N°: ',NEW.NUM_CPT,' a été débité de ', FORMAT(ROUND(NEW.SOLDE_ACTUEL - OLD.SOLDE_ACTUEL,2),2),
			 ', votre solde actuel est : ',FORMAT(NEW.SOLDE_ACTUEL,2)) ;
			INSERT INTO MESSAGE (DESTINATAIRE,MSG)
			VALUE
				(@DESTINATAIRE,@MSG);
		ELSEIF NEW.SOLDE_ACTUEL > OLD.SOLDE_ACTUEL THEN
			SET @MSG := CONCAT('N°: ',NEW.NUM_CPT,' a été crédité de ', FORMAT(ROUND(NEW.SOLDE_ACTUEL - OLD.SOLDE_ACTUEL,2),2),
			', votre solde actuel est : ',FORMAT(NEW.SOLDE_ACTUEL,2)) ;
			INSERT INTO MESSAGE (DESTINATAIRE,MSG)
			VALUE
				(@DESTINATAIRE,@MSG);

		END IF;
	END IF;

END