CREATE TRIGGER `MESSAGE_DEBLOC_MONTANT` AFTER UPDATE ON `solde_bloquer`
 FOR EACH ROW BEGIN
	DECLARE MSG VARCHAR(500);
	DECLARE DESTINATAIRE VARCHAR(100);

	SET @DESTINATAIRE := (SELECT Mail FROM CLIENT WHERE NUM_CPT=NEW.NUM_CPT) ;

	IF @DESTINATAIRE IS NOT NULL THEN

		SET @MSG := CONCAT('LE MONTANT : ',OLD.MT_BLOC,' A ETE  DEBLOQUER DANS VOTRE COMPTE TRESORE N°: ',NEW.NUM_CPT) ;
	    INSERT INTO MESSAGE (DESTINATAIRE,MSG)
		VALUE
				(@DESTINATAIRE,@MSG);
	END IF ;

END